iotech/models.py
from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin
from sqlalchemy.ext.declarative import declarative_base
from iotech.extensions import db




class User(UserMixin, db.Model):
    __tablename__ = "users"
    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(25), unique=True, nullable=False)
    password = db.Column(db.String(64), nullable=False)
    email = db.Column(db.String(100), nullable=False, unique=True)

    def __repr__(self):
        return '<User %r>' % self.username

iotech/__init__.py
from flask import Flask, render_template, redirect, request
from .models import User
import cv2
from .extensions import db, bootstrap, bcrypt, socketio, login_manager
from .routes.main import main
from .commands import create_tables

def create_app(config_file='settings.py'):

    app = Flask(__name__)

    app.config.from_pyfile(config_file)


    bcrypt.init_app(app)

    db.init_app(app)
    login_manager.init_app(app)
    login_manager.login_view = 'main.login'

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))
    
    bootstrap.init_app(app)
    socketio.init_app(app)
    app.register_blueprint(main)
    app.cli.add_command(create_tables)
    
    return app

iotech/routes/main.py
from flask import Flask, render_template, redirect, request, Response, Blueprint, url_for
import requests
from iotech.models import User
from iotech.wtform_fields import RegistrationForm, LoginForm
from flask_socketio import emit
from io import StringIO, BytesIO
import io
from PIL import Image
import PIL
import cv2
import imutils
import numpy as np
import base64
from iotech import cv2
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import img_to_array
from iotech.extensions import db, bcrypt, socketio
from flask_login import login_user, current_user, logout_user, logout_user, login_required

main = Blueprint('main', __name__)

@main.route('/')
def home():
    return render_template('home.html', form=None)


@main.route('/signup', methods=['GET', 'POST'])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('main.dashboard'))
    form = RegistrationForm(request.form)
    if form.validate_on_submit():
        username = form.username.data
        password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, password=password, email=form.email.data)

        db.session.add(user)
        db.session.commit()
        login_user(user)
        return redirect(url_for('main.home'))
    return render_template('signup.html', form=form)

@main.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.dashboard'))
    form = LoginForm(request.form)
    if form.validate_on_submit():
        username = form.username.data
        user = User.query.filter_by(username=username).first()
        if bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember= form.remember.data)
            return redirect(url_for('main.dashboard'))
        else:
            form.password.errors.append('incorrect password')

    return render_template('login.html', form=form)

@main.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@main.route('/dashboard')
@login_required
def dashboard():
    return render_template('dashboard.html')
    
classifier =load_model(r'iotech/static/assets/hand_gesture.h5')
labels = ['Five', 'Four', 'One', 'Three', 'Two']

@socketio.on("disconnect")
def socket_disconnect():
    print("disconnect")

@socketio.on('image')
def image(data):
    sbuf = StringIO()
    sbuf.write(data)
    b = io.BytesIO(base64.b64decode(data))
    pimg = Image.open(b)
    frame = cv2.cvtColor(cv2.flip(np.array(pimg), 1), cv2.COLOR_BGR2RGB)
    frame = cv2.flip(frame, 1)
    cv2.rectangle(frame, (50,50), (306,306), (0, 255, 255), 2)

    roi_rect = frame[50:306, 50:306]

    gray = cv2.cvtColor(roi_rect, cv2.COLOR_BGR2GRAY)
    _, thresh_binary = cv2.threshold(gray, 80, 255, cv2.THRESH_BINARY)
    roi_64 = cv2.resize(thresh_binary, (64, 64), interpolation=cv2.INTER_AREA)

    # IMAGE PREPROCESSING
    if np.sum([roi_64]) != 0:
        roi = roi_64.astype('float') / 255.0
        roi = img_to_array(roi)
        roi = np.expand_dims(roi, axis=0)

        # PREDICTION
        prediction = classifier.predict(roi)[0]
        label = labels[prediction.argmax()]

        cv2.putText(frame, label, (330,330), cv2.FONT_HERSHEY_SIMPLEX, 1, (0,255,255), 2)
        cv2.putText(frame, 'Accuracy - '+str(max(prediction)*100)[0:6], (20, 450), cv2.FONT_HERSHEY_SIMPLEX, 1, (0,255,255), 2)
    else:
        cv2.putText(frame, 'No Hands Detected', (30, 80), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
    # requests.get("http://192.168.1.10/"+label)
    # requests.get("http://")
    imgencode = cv2.imencode('.png', frame)[1]
    stringData = base64.b64encode(imgencode).decode('utf-8')
    b64_src = 'data:image/png;base64,'
    stringData = b64_src + stringData
    emit('response_back', stringData)

iotech/templates/base.html
{% import "bootstrap/wtf.html" as wtf %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    
    <title>Iotech</title>
    
    <link rel="icon" href="{{ url_for('static', filename='assets/logo.svg') }}" type="image/png">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='style/main.css') }}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600;700&display=swap" rel="stylesheet">
</head>
<body>
    
    <div class="ellipse">
        <img src="{{url_for('static', filename='assets/Ellipse_1.svg')}}">
    </div>
    
    <div class="circuit">
        <img src="{{url_for('static', filename='assets/circuit.svg')}}">
    </div>

    <div class="bellipse">
        <img src="{{url_for('static', filename='assets/Ellipse_2.svg')}}">
    </div>

    

    <nav class="row navbar navbar-expand-sm navbar-dark">
        <div class="logo col-8">    
            <a class="navbar-brand" href="#"><img src="{{ url_for('static', filename='assets/logo.svg') }}" alt="logo"> IoTech</a>
        </div>    
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            {% if current_user.is_authenticated %}
                <ul class="navbar-nav justify-content-around">
                    <li class="nav-item active">
                        <!-- <a class="nav-link btn btn-outline-success" data-toggle="modal" data-target="#signupModal" id="button-modal-login">Register</a> -->
                        <a class="nav-link btn btn-outline-success" href="{{url_for('main.logout')}}">Logout</a>
                    </li>
                </ul>
            {% else %}

                <ul class="navbar-nav justify-content-around">
                    <li class="nav-item active">
                        <!-- <a class="nav-link btn btn-outline-success" data-toggle="modal" data-target="#signupModal" id="button-modal-login">Register</a> -->
                        <a class="nav-link btn btn-outline-success" data-target="#signupModal" id="button-modal-login" href="{{url_for('main.signup')}}">Register</a>
                    </li>
                    <li class="nav-item active">
                        <!-- <a class="nav-link btn btn-outline-success" data-toggle="modal" data-target="#loginModal" id="button-modal-login">Sign in</a> -->
                        <a class="nav-link btn btn-outline-success" data-target="#loginModal" id="button-modal-login" href="{{url_for('main.login')}}">Sign in</a>
                    </li>
                </ul>

            {% endif %}
        </div>
    </nav>

    <div class="row align-content-center">
        <div class="girl col-6">
            <img class="girlsvg" src="{{ url_for('static', filename= 'assets/girl_tablet.svg') }}">
        </div>
        <div class="col text-white header-text">
            {% block modalClickHeader %}
            {% endblock %}
            <div class="row">
                <div class="col">
                    <a href="{{ url_for('main.dashboard') }}" class="dashboard btn btn-lg btn-outline-success">Dashboard</a>
                </div>
            </div>
        </div>
    </div>
    
    {% block signup %}
    {% endblock %}

    {% block login %}
    {% endblock %}
    
    
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/typeit@7.0.4/dist/typeit.min.js"></script>

    {% block scriptTypeHome %}
    {% endblock %}
    {% block scriptTypeSignup %}
    {% endblock %}

    <script>
        document.querySelector(".register-submit").onmousedown = (e) => {
            console.log("check")
            e.preventDefault()
        }
    </script>
    
    {% block signupModalScript %}
    {% endblock %}

    {% block loginModalScript %}
    {% endblock %}
    
</body>

</html>

iotech/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    
    <title>Iotech</title>
    
    <link rel="icon" href="{{ url_for('static', filename='assets/logo.svg') }}" type="image/png">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='style/dashboard.css') }}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600;700&display=swap" rel="stylesheet">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/opencv.js') }}"></script>
</head>
<body>
    <nav class="row navbar navbar-expand-sm navbar-dark">
        <div class="logo col-8">    
            <a class="navbar-brand" href="#"><img src="{{ url_for('static', filename='assets/logo.svg') }}" alt="logo"> IoTech</a>
        </div>    
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav justify-content-center">
                <li class="nav-item active">
                    <!-- <a class="nav-link btn btn-outline-success" data-toggle="modal" data-target="#signupModal" id="button-modal-login">Register</a> -->
                    <a class="nav-link btn btn-outline-success" id="Logout" href="{{url_for('main.logout')}}">Logout</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="row">
        <div class="col-6">
            <div id="canvasContainer">
                <canvas id="canvasOutput" height= "375" width="500"></canvas>
            </div>
                <video autoplay="true"  style="display:none;" id="videoElement"></video>
                <canvas id="temp" height="375" width="500" style="height: 375; width: 500; display:none;">
                </canvas>

            <div class = 'video'>
                <img id="image">
            </div>
            

            <div class="row vid-button">
                <div class="col-4 offset-4">
                    <a class="btn btn-danger" href="{{ url_for('main.home') }}">stop</a>
                </div>            
            </div>
        </div>
        <div class="col">
            <div class="container">
                <div class="row align-text-center">
                    <div class="col-6">
                        <h4>Temperature</h4>
                    </div>
                    <div class="col">
                        <h4>
                            humidity
                        </h4>
                    </div>
                </div>
                <div class="row">
                    <div class="col offset-3">
                        <h3>Appliance being controlled:</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>


        <script>
            var socket = io.connect('http://'+document.domain+':'+ location.port);
        
            socket.on('connect', function(){
                console.log("Connected...!", socket.connected)
            });
    
            socket.on('response_back', function(stringData){
                // console.log(stringData)
                var canvas = document.getElementById('canvasOutput')
                var ctx = canvas.getContext("2d")
                var image_new = new Image()
                image_new.onload = function(){
                    ctx.drawImage(image_new, 0,0, 500, 375)
                }
                image_new.src = stringData
                
                // ctx.drawImage(stringData, 0, 0)
            })
        
            const video = document.querySelector("#videoElement");
        
            video.width = 600; 
            video.height = 375;
                if (navigator.mediaDevices.getUserMedia) {
                    navigator.mediaDevices.getUserMedia({ video: true })
                    .then(function (stream) {
                        video.srcObject = stream;
                        video.play();
                    })
                    .catch(function (err0r) {
                        console.log(err0r)
                        console.log("Something went wrong!");
                    });
                }
            var cap
            var src
            var dst
                cv['onRuntimeInitialized']=()=>{
                    src = new cv.Mat(video.height, video.width, cv.CV_8UC4);
                    dst = new cv.Mat(video.height, video.width, cv.CV_8UC1);
                    cap = new cv.VideoCapture(video);
                    const FPS = 22;
                    setInterval(() => {
                        cap.read(src);
                
                        var type = "image/png"
                        var canvas = document.getElementById('temp');     
                        var data = document.getElementById("videoElement")    //.toDataURL(type);
                        canvas.getContext('2d').drawImage(data, 0, 0, 500, 375);       
                        var base64 = canvas.toDataURL().replace('data:' + type + ';base64,', '')  
                        //data = data.replace('data:' + type + ';base64,', ''); //split off junk at the beginning
                        socket.emit('image', base64);
                    }, 10000/FPS);
                };
            
            
            
        
        
            // socket.on('response_back', function(image){
            //     const image_id = document.getElementById('image');
            //     image_id.src = image;
            // });
        
        </script>
</body>
</html>

iotech/templates/home.html
{% extends 'base.html' %}
{% block modalClickHeader %}
<h1 id="typed-text"></h1>
{% endblock %}

{% block scriptTypeHome %}
<script>
    new TypeIt("#typed-text", {
    strings: "All Appliances at your fingertips...",
    speed: 75,
    loop: false,
    cursor: true
    }).go();
</script>
{% endblock %}

iotech/templates/login.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block modalClickHeader %}
<h1>All appliances at your finger tips..<span><h1 style="display:inline-flex;" id="typed-text"></h1></span></h1>
{% endblock %}

{% block login %}
<div class="modal fade" id="loginModal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header text-center border-bottom-0">
                <h3 class="modal-title text-center ">Sign in</h3>
                <button class="close" data-dismiss="modal"><span class="cross" aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <form action="{{ url_for('main.login') }}" method="POST">
                    {{ form.hidden_tag() }}
                    {{ wtf.form_field(form.username) }}
                    {{ wtf.form_field(form.password) }}
                    {{ wtf.form_field(form.remember) }}
                    <!-- <div class="form-group row">  
                        <div class="col-1"></div>                              
                        <div class="col-2">
                            <label for="username" class="col-form-label">
                                <img class="mansvg" src="{{ url_for('static', filename= 'assets/man.svg') }}">
                            </label>
                        </div>
                        
                        <div class="col-7">
                            {{ form.username(class_='form-control register-input', placeholder='Username', autocomplete='off', autofocus=true) }}
                            <ul>
                                {% for error in form.username.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-1"></div>                              
                        <div class="col-2">
                            <label for="password" class="col-form-label">
                                <img class="keysvg" src="{{ url_for('static', filename= 'assets/key.svg') }}">
                            </label>
                        </div>
                        <div class="col-7">
                            {{ form.password(class_='form-control register-input', placeholder='password') }}
                            <ul>
                                {% for error in form.username.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    
                    <div class="form-group row justify-content-center align-content-center"> 
                        <div class="col-2"></div>
                        <div class="col-8 align-self-center">
                            <input class="register-submit btn btn-outline-success btn-lg" id="registerSubmit" type="submit" value="Login">
                        </div>
                        <div class="col-2"></div>
                    </div>
                    {{ form.csrf_token }} -->
                    <div class="col-8 offset-2 align-self-center">
                        <input class="register-submit btn btn-outline-success btn-lg" id="registerSubmit" type="submit" value="Login">
                    </div>
                </form>                        
            </div>
        </div>
    </div>
</div>
{% endblock %}



{% block loginModalScript %}
<script type="text/javascript">
    $(window).on('load', function() {
        $('#loginModal').modal('show');
    });
</script>    
{% endblock %}

{% block scriptTypeSignup %}
<script>
    new TypeIt("#typed-text", {
    strings: ".",
    speed: 75,
    loop: false,
    cursor: true
    }).go();
</script>
{% endblock %}


<!-- <form action="{{ url_for('signup') }}" method="POST">
        
    <div>
        {{ form.username(class_='form-control', placeholder='Username', autocomplete='off', autofocus=true) }}
        <ul>
            {% for error in form.username.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    </div>
    <div>
        {{ form.password(class_='form-control', placeholder='password') }}
        <ul>
            {% for error in form.username.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    </div>
    <div>
        {{ form.confirm_password(class_='form-control', placeholder='re-type password') }}
        <ul>
            {% for error in form.username.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    </div>
    <div>
        <input type="submit" value="signup">
    </div>
    {{ form.csrf_token }}
</form> -->

iotech/templates/signup.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block modalClickHeader %}
<h1>All appliances at your finger tips..<span><h1 style="display:inline-flex;" id="typed-text"></h1></span></h1>
{% endblock %}


{% block signup %}
<div class="modal fade" id="signupModal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header text-center border-bottom-0">
                <h3 class="modal-title text-center ">Register</h3>
                <button class="close" data-dismiss="modal"><span class="cross" aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <form action="{{ url_for('main.signup') }}" method="POST">
                    {{ form.hidden_tag() }}
                    {{ wtf.form_field(form.username) }}
                    {{ wtf.form_field(form.email) }}
                    {{ wtf.form_field(form.password) }}
                    {{ wtf.form_field(form.confirm_password) }}
                    
                    <!-- <div class="form-group row">  
                        <div class="col-1"></div>                              
                        <div class="col-2">
                            <label for="username" class="col-form-label">
                                <img class="mansvg" src="{{ url_for('static', filename= 'assets/man.svg') }}">
                            </label>
                        </div>
                        
                        <div class="col-7">  
                                {{ form.username(class_='form-control register-input', placeholder='Username', autocomplete='off', autofocus=true) }}
                                
                                <ul>
                                    {% for error in form.username.errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                </ul>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-1"></div>                              
                        <div class="col-2">
                            <label for="password" class="col-form-label">
                                <img class="keysvg" src="{{ url_for('static', filename= 'assets/key.svg') }}">
                            </label>
                        </div>
                        <div class="col-7">
                                {{ form.password(class_='form-control register-input', placeholder='password') }}
                                <ul>
                                    {% for error in form.username.errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                </ul>
                            
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-1"></div>                              
                        <div class="col-2">
                            <label for="confirm_password" class="col-form-label">
                                <img class="keysvg" src="{{ url_for('static', filename= 'assets/key.svg') }}">
                            </label>
                        </div>
                        <div class="col-7">
                                {{ form.confirm_password(class_='form-control register-input', placeholder='re-type password') }}
                                <ul>
                                    {% for error in form.username.errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                </ul>
                        
                        </div>
                    </div>
                    <div class="form-group row justify-content-center align-content-center"> 
                        <div class="col-2"></div>
                        <div class="col-8 align-self-center">
                            <input class="register-submit btn btn-outline-success btn-lg" id="registerSubmit" type="submit" value="Signup">
                        </div>
                        <div class="col-2"></div>
                    </div>
                    {{ form.csrf_token }} -->
                    <div class="col-8 offset-2 align-self-center">
                        <input class="register-submit btn btn-outline-success btn-lg" id="registerSubmit" type="submit" value="Signup">
                    </div>
                </form>                        
            </div>
        </div>
    </div>
</div>
{% endblock %}


{% block signupModalScript %}
<script type="text/javascript">
    $(window).on('load', function() {
        $('#signupModal').modal('show');
    });
</script>
{% endblock %}



{% block scriptTypeSignup %}
<script>
    new TypeIt("#typed-text", {
    strings: ".",
    speed: 75,
    loop: false,
    cursor: true
    }).go();
</script>
{% endblock %}